import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gimletDisplay = localFont({
    src: "../public/fonts/GimletDisplayCompressed-Italic-Testing.woff2",
    variable: "--font-heading",
    style: "italic",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={gimletDisplay.variable}>
            <body>{children}</body>
        </html>
    );
}
